<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AssemblyVersion>0.0.0.1</AssemblyVersion>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Windows\Confirmation.axaml.cs">
        <DependentUpon>Confirmation.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
        <Compile Update="Windows\Synchronize.axaml.cs">
            <DependentUpon>Synchronize.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
      <Compile Update="Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="App.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <Target Name="DeleteSkiaPdbs" AfterTargets="Publish">
        <Delete Files="$(PublishDir)libSkiaSharp.pdb;$(PublishDir)libHarfBuzzSharp.pdb" />
    </Target>
</Project>
